### ISSUE TITLE
validation prevents parent menu creation ("edit mode")

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/StructureManager#11]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

![image](https://user-images.githubusercontent.com/932193/46954780-c0e70100-d091-11e8-810d-6e9a3ac2b8ee.png)

### Steps to Reproduce
1. Try creating a structure with only a (parent) menu

### Expected behavior

link to not be required so that generation can happen; or to be ignored so validation can still happen

### Actual behavior

link must be of type string & link must be empty

**Comment by jlsjonas** [comment]
Note, it only happens if you enter the menu configuration for a 2nd time

**Comment by aocneanu** [comment]
Unable to reproduce

**Comment by jlsjonas** [comment]
@aocneanu did you fill in a menu entry to then edit it? (the bug only appears in the _edit mode_, as described)

**Comment by aocneanu** [comment]
I did
