### ISSUE TITLE
Support creating multiple menu items

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/StructureManager#12]
This is  a **feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

In certain cases, it's preferable to have multiple links in the menu (depending on permissions) for one structure.

of course, we could just create an extra structure migration but this won't always make sense (and could easily cause class name collisions I believe).

I'd suggest replacing `$menu` with `$menus`, an array of arrays; instead.
(to prevent complicating the CLI further we could manually add extra rows?)

use case: direct link to form besides the index

**Comment by aocneanu** [comment]
In Enso the convention for a *structure* is what the structure migration is currently allowing. Menu related, this means exactly 1 possible menu (possible = optional) in per structure. 

If you have 2 or more menus from Enso's perspective you have 2 or more structures.

(anyway, creating a new structure migration for only 1 menu will take about 5-10 extra seconds)

A team of people is currently relying on the current workflow / convention set / standard that was defined over some years. The proposed feature is not compatible with it.

**Comment by jlsjonas** [comment]
>(anyway, creating a new structure migration for only 1 menu will take about 5-10 extra seconds)

I completely agree, but in case of related menu items to the main structure it feels like an anti-pattern

>A team of people is currently relying on the current workflow / convention set / standard that was defined over some years. The proposed feature is not compatible with it.

isn't it a superset of the current situation? the current workflow/conventions/standard could still be used with the suggested change, the only real difference would be that the StructureMigration would have to support looping through `$menus` vs just generating 1 `$menu`

For backwards-compatibility, handling `$menu` would have to be kept either way (wrapping it in an array before executing `$menus` logic) so even if the migration structures are manually written the old way would still work (without adding much complexity)

It's your framework though 😉

**Comment by jlsjonas** [comment]
+ as our implementation got further; a possible future expansion this could allow would be "grouping"/tagging menus so that only 1 of them would be highlighted without specific code (if we end up writing generic enough code for this part I'll PR it)

**Comment by jlsjonas** [comment]
>so that only 1 of them would be highlighted without specific code (if we end up writing generic enough code for this part I'll PR it)

PR coming up

**Comment by aocneanu** [comment]
>isn't it a superset of the current situation

it is, but still contradicts the convention. We're not into adding every possible feature, we're  in adding features that we need and are consistent with what's already there.

>+ A possible future expansion this could allow would be "grouping"/tagging menus so that only 1 of them would be highlighted without specific code (if we end up writing generic enough code for this part I'll PR it)

You lost me here. Give me some more details, maybe an example

**Comment by jlsjonas** [comment]
>it is, but still contradicts the convention.

👍 

>You lost me here. Give me some more details, maybe an example

We need a direct link to the create page on certain models; in the current code this would cause both items to be highlighted (see the referenced PR, and let's continue there as it's a slightly different issue.

Will close this one as it's not matching the convention (although I think it could be a good addition to it; that's just one workflow vs the other.)
