### ISSUE TITLE
Validation prevents empty menu creation

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/StructureManager#13]
This is  a **bug | feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

creating a menu-only structure seems to have broken due to validation
![image](https://user-images.githubusercontent.com/932193/47141368-caa27b80-d2c0-11e8-9ee6-706f3bc0afe1.png)

### Steps to Reproduce
1. Try creating a new menu-only generation via structure manager
2. On generate, permission group definition validation happens

### Expected behavior

Menu-only structure migration to be created

### Actual behavior

Validation error

**Comment by aocneanu** [comment]
It not really a bug when the validation works :D

Maybe we should add an option to the CLI to ignore validations ..

**Comment by aocneanu** [comment]
>the validation isn't triggered with parent menu creation;
>it works for parent-menus, btw

the validation is triggered, it's just different.

You can see [here](https://github.com/laravel-enso/MenuManager/blob/master/src/app/Http/Requests/ValidateMenuRequest.php#L27) the intended validations for menus.

**Comment by jlsjonas** [comment]
>the validation is triggered, it's just different.

Sorry, I meant it doesn't throw.
