### ISSUE TITLE
Validation forcing convention

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/StructureManager#14]
This is  a **feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

The cli should validate according to the expected convention, or even better don't ask the convention-based requirements (link between model, menu, ...)

I encountered yet another case that (as we don't constantly use/need the structure manager) I created a structure that fails on itself (as "categories" is a very generic model name, I prepended it with the _parent_ route; this is causing breaking including inside the sql ("unknown column" as it's trying to find a `tablename.id` that doesn't exist)

### Steps to Reproduce

1. structure generation that doesn't exactly follows the convention

### Expected behavior

Either an error or a correct generation that works

### Actual behavior

Structure gets generated that just doesn't work

**Comment by aocneanu** [comment]
I really tried to reproduce the issue as you instructed but I couldn't do step 1 :))

**Comment by jlsjonas** [comment]
the following structure file got created:
```php
<?php

use LaravelEnso\StructureManager\app\Classes\StructureMigration;

class CreateStructureForDamageCategories extends StructureMigration
{
    protected $permissionGroup = ['name' => 'tool.categories', 'description' => 'ToolCategories Permission Group'];
    
    protected $permissions = [
        ['name' => 'tool.categories.index', 'description' => 'Show index for tool category', 'type' => 0, 'is_default' => false],
        ['name' => 'tool.categories.create', 'description' => 'Create tool category', 'type' => 1, 'is_default' => false],
        ['name' => 'tool.categories.store', 'description' => 'Store a new tool category', 'type' => 1, 'is_default' => false],
        ['name' => 'tool.categories.edit', 'description' => 'Edit tool category', 'type' => 1, 'is_default' => false],
        ['name' => 'tool.categories.update', 'description' => 'Update tool category', 'type' => 1, 'is_default' => false],
        ['name' => 'tool.categories.destroy', 'description' => 'Delete tool category', 'type' => 1, 'is_default' => false],
        ['name' => 'tool.categories.initTable', 'description' => 'Init table for tool category', 'type' => 0, 'is_default' => false],
        ['name' => 'tool.categories.getTableData', 'description' => 'Get table data for tool category', 'type' => 0, 'is_default' => false],
        ['name' => 'tool.categories.options', 'description' => 'Get tool category options for select', 'type' => 0, 'is_default' => false],
    ];

    protected $menu = [
        'name' => 'Categories', 'icon' => 'list-ol', 'link' => 'tool.categories.index', 'order_index' => 200, 'has_children' => false
    ];

    protected $parentMenu = 'Tool';
}
```

with the following `api.php` snipper

```php

Route::namespace('Tool\Categories')
    ->prefix('tool/categories')->as('tool.categories.')
    ->group(function () {
        Route::get('initTable', 'ToolCategoryTableController@init')
            ->name('initTable');
        Route::get('getTableData', 'ToolCategoryTableController@data')
            ->name('getTableData');
        Route::get('exportExcel', 'ToolCategoryTableController@excel')
            ->name('exportExcel');

        Route::get('options', 'ToolCategorySelectController@options')
            ->name('options');
    });

Route::namespace('Tool\Categories')
    ->prefix('tool')->as('tool.')
    ->group(function () {
        Route::resource('toolCategories', 'ToolCategoryController'); // if it's the case, use `except` or `only` to avoid generating unused routes
    });
```

the route would have to be `tool.toolCategories.` for anything ToolCategoryController manages; instead of _the expected_ `tool.categories`

**Comment by aocneanu** [comment]
you specifically wrote the permissionGroup like that.

>protected $permissionGroup = ['name' => 'tool.categories', 'description' => 'ToolCategories Permission Group'];

Routes are only appended to the PG. The pg is read from the `name` prop, not from `description` :)

**Comment by jlsjonas** [comment]
>you specifically wrote the permissionGroup like that.

Maybe I worded incorrectly; I'm fully aware the permissiongroup is `tool.categories`, which is also what I want it to be

However; the generated code expects it to be `tool.toolCategories` instead
possibly a bug in the api snippet generation code

**Comment by aocneanu** [comment]
ah got it.

The `resource('toolCategories')` is generated using the model as a source. So if the model is `ToolCategory` instead of `Category` then this is what you get.

**Comment by aocneanu** [comment]
[laravel-docs](https://laravel.com/docs/5.7/controllers#resource-controllers)

**Comment by jlsjonas** [comment]
The model has to be named like that to not get name collisions though (and `tool.toolCategories` as the route doesn't make sense IMHO)

**Comment by jlsjonas** [comment]
![image](https://user-images.githubusercontent.com/932193/47156944-7c08d780-d2e8-11e8-8d97-725b392bb817.png)
Not sure what happened last time around... getting an error this time 😅 
Sorry for the confusion.

**Comment by jlsjonas** [comment]
never mind... I just forgot to add `.index` this time 😅

**Comment by jlsjonas** [comment]
It seems that (except for a FE --likely caching-- related issue I'm still trying to figure out) the main change is that in the generated code
```php
        Route::resource('toolCategories', 'ToolCategoriesController');
```

would have to be replaced with
```php
        Route::resource('categories', 'ToolCategoriesController');
```

**Comment by aocneanu** [comment]
IM(H)O it wouldn't make sense to have a resource called categories, the model binding to be made by `{category}` and expect that that to be a `ToolCategory` model.

Add a`Tools` directory where you will keep all the tool related models and you'll have something cleaner. `App\Tools\Category`

**Comment by jlsjonas** [comment]
There's actually 1 more issue beside what I mentioned above...
`Column not found: 1054 Unknown column 'toolCategories.id' in 'field list` where it should be `tool_categories` 🤔

**Comment by jlsjonas** [comment]
>and expect that that to be a ToolCategory model.

100% correct; that was a typo from the investigation 😅

**Comment by aocneanu** [comment]
finally an actual bug!

**Comment by jlsjonas** [comment]
Do I create a separate issue for (the very related) https://github.com/laravel-enso/StructureManager/issues/14#issuecomment-431009957 ?
