### ISSUE TITLE
Structure generation crashes on clean db

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/StructureManager#15]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

While pinning down the route source of/solution for #14 I rolled back my migrations causing the menus table to not exist.

This causes a fatal
![image](https://user-images.githubusercontent.com/932193/47156447-719a0e00-d2e7-11e8-8d7b-35a37c4735ee.png)

### Steps to Reproduce
1. create structure via the structuremanager without a menus table present (fresh db, no migrations ran//all rolled back)

### Expected behavior

I believe it should instead either continue with a warning (as it couldn't verify the parent exists; but it also doesn't need it as it's the migration itself that handles that) or alternatively recover from the error so you don't have to input everything all over again

### Actual behavior

Fatal error losing configuration

**Comment by jlsjonas** [comment]
Looks like it doesn't even do anything with it, I made a typo where I used the plural form in the creation; yet everything still went through

**Comment by aocneanu** [comment]
>I believe it should instead either continue with a warning (as it couldn't verify the parent exists; but it also doesn't need it as it's the migration itself that handles that)

What would be the point of the validation then?

>recover from the error so you don't have to input everything all over again

so in situations when you "forget" to migrate, it would allow you to open a new tab, migrate and after retry right?

What about just migrate, then use the structure ?

**Comment by jlsjonas** [comment]
>so in situations when you "forget" to migrate, it would allow you to open a new tab, migrate and after retry right?

Exactly 😁 

>What about just migrate, then use the structure ?

The thing is, in development (where you often do a `:refresh` or `:fresh` migration it can happen that you rollback actually rolls back everything instead of only the _just added_ migration.

Alternatively maybe check if menus is there when starting the tool? (which would add a slight startup penalty 😅 )

**Comment by aocneanu** [comment]
You can ref this when you'll open the PR
