### ISSUE TITLE
StructureManager is barely compatible with generic names

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/StructureManager#16]
This is a **bug**

# Description
(from https://github.com/laravel-enso/StructureManager/issues/14#issuecomment-431009957)
> It seems that the main change is that in the generated code

> ```php
        Route::resource('toolCategories', 'ToolCategoriesController');
```

> would have to be replaced with
> ```php
        Route::resource('categories', 'ToolCategoriesController');
```

i.e. the resource key is using the model as basis instead of the permission group

# Steps to Reproduce
1. generate structure with difference between permission group _last key_ and model name (f.e. `tool.categories` and `ToolCategory`

# Expected behavior

Model name not to influence route key

# Actual behavior

Route key seems to be based on the plural of the model name instead

**Comment by jlsjonas** [comment]
Laravel restriction (edit etc.) doesn't detect the model otherwise; too bad.

**Comment by aocneanu** [comment]
Deep down, I was reeally hoping for this :)))

I'm all about conventions, so for me it's GREAT:D

But you can always open an issue on laravel/framework and ask Taylor to reconsider his conventions.

**Comment by jlsjonas** [comment]
It's caused issues for others as well (since pre 5.0) with no avail so I'll just leave it for what it is and figure another way to organize the models...

Maybe this would be a good time to poke about structuring models according to the permission group in the structure manager? otherwise, the 2nd `categories` I'll have to make will cause a collision

**Comment by jlsjonas** [comment]
this is actually causing a lot of name conflicts, going to reopen this and rewrite towards what the actual issue is:
- a lot of files generated using a generic name
- database table generated using a generic name

**Comment by aocneanu** [comment]
>StructureManager is barely compatible with generic names

?@#
