### ISSUE TITLE
Routing problems

### ISSUE THREAD

**Issue by eo22** [laravel-enso/StructureManager#2]
This is  a help request.

### Prerequisites
* [+ ] Are you running the latest version?
* [ +] Are you reporting to the correct repository?
* [ +] Did you check the documentation?
* [ +] Did you perform a cursory search?

### Description
I've created cli structure step by step as is described in documentation and it creates all : permission group, permissions, menus etc, but I have some errors on console(img1) about missing routes but I've pasted the code of route on api.php (img2).

![screen shot 2018-08-03 at 16 34 10](https://user-images.githubusercontent.com/37216194/43648590-1f88fb0e-973b-11e8-91c2-2a1c3671e429.png)
![screen shot 2018-08-03 at 16 34 58](https://user-images.githubusercontent.com/37216194/43648620-3ebfb152-973b-11e8-9201-9d85a1ad1e4f.png)

Thanks a lot!

**Comment by aocneanu** [comment]
did you ran the migration(s)?

**Comment by eo22** [comment]
When I try to run migrations, there's an error:
![screen shot 2018 08 06 at 09 58 27](https://user-images.githubusercontent.com/37216194/43704292-7a682894-995f-11e8-8036-928c1ed9e625.png)

**Comment by aocneanu** [comment]
This is not related to Enso

You should be able to easily determine what's causing this  in your ecosystem.
