### ISSUE TITLE
CLI is not working properly

### ISSUE THREAD

**Issue by albertosgz** [laravel-enso/StructureManager#20]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
After set all options and generate the files, only the migration is done.
I'm using Enso version 2.13.7 (commit e68f80d07d43efe81fd06743cb42f159aa82769e), on Laradock, version of Sat Oct 27, commit 538b6aa0cd484c475c5c537a763e4e1fe330fcae.

### Steps to Reproduce

1. php artisan enso:make:structure
2. set all options
3. generate files

### Expected behavior
To have new files for Form, Model, etc.

### Actual behavior
Only the migration is created
![image](https://user-images.githubusercontent.com/12124175/48067993-f0d97e00-e1d1-11e8-815c-2f31a54c5a8b.png)

**Comment by aocneanu** [comment]
![image](https://user-images.githubusercontent.com/16073274/48072806-06f13980-e1e6-11e8-983c-c7b5a3013ff5.png)

This means that you did not configure the files to be generated. By default only the structure migration is created. 

(as instructed) 
![image](https://user-images.githubusercontent.com/16073274/48072865-1f615400-e1e6-11e8-8453-b158669335e4.png)

**Comment by albertosgz** [comment]
I'm sorry! it's true, it's a little embarrassing.... I've tested several times, and always I jumped that step.
Thanks!
