### ISSUE TITLE
Structure manager not updated with 2.13.16 changes

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/StructureManager#21]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
vue-form-ss got replaced with enso-form in 2.13.16, however StructureManager is still generating them.

We should check for possible other inconsistencies towards latest updates before closing this, as latest is 2.14.0 meanwhile

### Steps to Reproduce
generate a structure

### Expected behavior

using latest structure

### Actual behavior

still generating vue-form-ss, which is no longer supported

**Comment by aocneanu** [comment]
fixed in aca13749cacb9b961ca0bcb1938db30504b5b652

**Comment by aocneanu** [comment]
Seems that it was the only inconsistency, if we'll find anything else we'll open a new ticket.
