### ISSUE TITLE
Support generating menu for "2nd" occurence

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/StructureManager#22]
This is  a **feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

Currently, the menu name is used to fetch the parent id from the database during structure generation.
This works great when all menus have unique names, however when your structure _requires_ multiple parent menus with the same name ("admin" section per subsection, for example) the system becomes inflexible very quickly.

### Steps to Reproduce
1. Have 2 "parent"menus (has_children = true) with the same name
2. When generating a structure, all entries would get added to the _first_ one

### Expected behavior

Either
1) (easiest to implement) allow defining an id instead
  drawback: relying on existing structure, migration might cause unforeseen problems if id's don't match

2) (most flexible) Use (similar to permission groups) the dotted notation to match including parents.
For example:
`parent: example.admin` would create a menu entry under the menu with name `admin` which is a child of `example`

### Actual behavior

creating entry under first occurence.

**Comment by aocneanu** [comment]
2. kinda sense.
