### ISSUE TITLE
Unknown custom element: <vue-table>  in Index.vue

### ISSUE THREAD

**Issue by Benoit75** [laravel-enso/StructureManager#27]
This is  a **bug**.

### Prerequisites
* [X] Are you running the latest version?
fresh install
* [X] Are you reporting to the correct repository?
* [X] Did you check the documentation?
* [X] Did you perform a cursory search?

### Description

In a full Enso environment, using StructureManager generate index.vue with vue-table and after a yarn dev, the component was not found

<template>
    <vue-table class="box is-paddingless raises-on-hover"
        id="timesheetactivities"/>
</template>
<script>
import VueTable from '@enso-ui/tables/bulma';
export default {
    name: 'Index',
    components: {  VueTable  },
};
</script>

### Expected behavior

Generate Index.vue with EnsoTable instead of VueTable

### Actual behavior

Error message : [Vue warn]: Unknown custom element: <vue-table> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

Thank's for this amazing environment
Regards

**Comment by aocneanu** [comment]
a composer `update && yarn upgrade && yarn run dev` will fix the problem.

i will publish a new release a soon with this and many more fixed.

**Comment by aocneanu** [comment]
published
