### ISSUE TITLE
Not working on windows

### ISSUE THREAD

**Issue by boing6000** [laravel-enso/StructureManager#3]
Bug

### Prerequisites
* [v ] Are you running the latest version?
* [v ] Are you reporting to the correct repository?
* [v ] Did you check the documentation?
* [v ] Did you perform a cursory search?

### Description
Not working in Windows

### Expected behavior
Steps to create the structure

### Actual behavior
![image](https://user-images.githubusercontent.com/3080041/44263506-998cc880-a1f5-11e8-9f7c-86f67c2b8536.png)

**Comment by jlsjonas** [comment]
I can confirm it does work on windows (I'm using Laragon with Cmder myself too so that's not the cause of the issues)

@aocneanu As you see in the screenshot it seems to just exit when executed instead of giving the interactive menu (some dependency missing, maybe?)

**Comment by aocneanu** [comment]
@boing6000 It seems that it's something related to your specific env...

**Comment by boing6000** [comment]
If someone has the same problem, i removed the vendor path and executed composer install again, and everithing worked fine.
