### ISSUE TITLE
Camel/snake/lower-casing issues

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/StructureManager#9]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

After #4 from Yesterday, it seems that there are more discrepancies with casing.
One of the next issues I stumbled upon was/is the generated controllers not matching the generated route:
the generated `::resource` gets `fooBars` which makes Laravel _magically_ attach the correct resource to `fooBar` in the controller; however in the controller the parameter name is `$foobar` (instead of `$fooBar`)

also see https://github.com/laravel/framework/issues/18167

### Steps to Reproduce

1. Generate structure with CamelCased Model
2. notice discrepancy between route & controller

### Expected behavior

see Description

### Actual behavior

Mismatch causing _magic_ to fail.

**Comment by aocneanu** [comment]
Let's fix the magic ...
